import "../styles/global.scss";
import localFont from 'next/font/local'
import { Roboto } from 'next/font/google';
import type { Metadata } from "next";

const uniSans = localFont({
  src: [
    {
      path: '../../assets/fonts/Uni Sans Heavy.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-uni-sans'
})

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700"],
  subsets: ['latin'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${uniSans.variable} ${roboto.variable}`}>
        {children}
      </body>
    </html>
  );
}
